"""Registry data slice: the wearable intimacy accessories and usable intimacy devices roster.

Moved verbatim from the ``ITEM_REGISTRY`` literal in
``world/lore/items.py``; ``ROWS`` is the contiguous, in-order
entry block (section comments included) the assembly concatenates.
Do not reorder or edit rows here: registry order is observable.
"""

from world.lore.items.vocab import (
    ItemUseMechanics,
    ItemPresentation,
    ItemDefinition,
    EquipmentModifierKey,
    ItemKind,
    ItemIconKey,
    ItemRarity,
)

from world.skills.equipment import EquipmentSlot

ROWS: tuple[ItemDefinition, ...] = (
        # Wearable intimacy accessories (add-toy-item-category)
        ItemDefinition(
            key="nymph_buds_clamp",
            display_name_zh="花蒂銀夾",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="聖所銀匠打的細銀乳夾，服儀的一部分，夾住之後每一口呼吸、每一步走動都被反覆輕錐，癢得發燙也摘不下手。",
            ),
            equipment_slot=EquipmentSlot.ACCESSORY,
            modifier_key=EquipmentModifierKey.NYMPH_BUDS_CLAMP,
        ),
        ItemDefinition(
            key="warm_honey_orb",
            display_name_zh="暖蜜魔導珠",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="聖所器具店常見貨色裡的蜜色魔導珠，以體溫為動力源源不絕地暖磨最敏感的那處，一戴就是一整日。",
            ),
            equipment_slot=EquipmentSlot.ACCESSORY,
            modifier_key=EquipmentModifierKey.WARM_HONEY_ORB,
        ),
        ItemDefinition(
            key="hyperesthesia_charm",
            display_name_zh="尖銳觸感之飾",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="聖所販售的祝禱掛飾，效果直白：佩戴期間皮膚的觸感被整體放大，衣料摩擦都變成細密的電流，平日無感的輕觸都會一路鑽進神經，從早到晚渾身不對勁。",
            ),
            equipment_slot=EquipmentSlot.ACCESSORY,
            modifier_key=EquipmentModifierKey.HYPERESTHESIA_CHARM,
        ),
        ItemDefinition(
            key="warmth_rune_egg",
            display_name_zh="恆溫魔法卵",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="刻入恆溫魔法陣的鵝卵石小卵，含在體內便持續溫熱下體、催出潤澤，外頭沒人看得出來。",
            ),
            equipment_slot=EquipmentSlot.ACCESSORY,
            modifier_key=EquipmentModifierKey.WARMTH_RUNE_EGG,
        ),
        ItemDefinition(
            key="tremor_crystal",
            display_name_zh="恆振晶",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.RARE,
                summary_zh="精靈匠作的乳色魔導晶，刻著人類學者讀不懂的微振術式，貼身藏好便能以恆定微顫終日刺激花心，術式撐到下次造訪精靈村前從不停歇。",
            ),
            equipment_slot=EquipmentSlot.ACCESSORY,
            modifier_key=EquipmentModifierKey.TREMOR_CRYSTAL,
        ),
        # Usable intimacy devices (land-usable-intimacy-items)
        ItemDefinition(
            key="aphrodisiac_bath_salts",
            display_name_zh="催情浴鹽",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="浴場的招牌入浴劑，泡完整個皮膚的敏感度輕飄飄地抬高整個晚上，冒險歸來的定番享受。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=True,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="kiss_of_goddess_mist",
            display_name_zh="女神之吻聖霧",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.RARE,
                summary_zh="聖所「女神之吻」禮儀聖霧的裝瓶紀念品，一噴讓全身敏感度瞬間拉到頂，信徒把它當成能帶回家的神蹟。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=False,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="censer_of_desire",
            display_name_zh="情欲香爐",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.RARE,
                summary_zh="聖所禮儀用的小巧香爐，爐煙沾上肌膚就化作綿長酥癢，越是動情燒得越是歡。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=False,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="embracing_vine",
            display_name_zh="纏枝魔藤",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.RARE,
                summary_zh="一盆栽在陶盆裡的魔法藤蔓，澆水醒來後會溫柔地纏上全身每一處敏感地，以恰好不弄傷人的力道緩慢收緊磨蹭，一個季度後自己縮回盆裡沉睡，等下次澆水再醒。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=False,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="spark_candy",
            display_name_zh="微電跳蛋糖",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="含在嘴裡就對舌頭送微電流的神奇糖果，電流順著神經一路麻到下半身；外表和普通糖果無異，不知情的孩子常常誤食，附魔師公會因此被投訴過很多次。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=True,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="slime_lube_gel",
            display_name_zh="史萊姆潤滑凝膠",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="〔素材〕史萊姆黏液的下游製品：滅菌處理過的黏液分裝包，滑潤持久怎麼塗都不會乾，讓摩擦的每一寸都變成放大的觸感。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=True,
                combat_allowed=False,
            ),
        ),
        ItemDefinition(
            key="hot_kiss_potion",
            display_name_zh="熱吻藥水",
            price_table_key="intimacy_tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOY,
                icon_key=ItemIconKey.TOY,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="喝下去從舌頭一路暖到小腹的粉紅藥劑；鍊金坊的正經生意，櫃檯前永遠站著情侶和新婚夫妻。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=True,
                combat_allowed=False,
            ),
        ),
)
