"""Registry data slice: the original guild-economy roster (basic food, potions, weapons and the first equipment line).

Moved verbatim from the ``ITEM_REGISTRY`` literal in
``world/lore/items.py``; ``ROWS`` is the contiguous, in-order
entry block (section comments included) the assembly concatenates.
Do not reorder or edit rows here: registry order is observable.
"""

from world.lore.items.vocab import (
    ItemUseMechanics,
    ItemPresentation,
    ItemDefinition,
    EquipmentModifierKey,
    ItemKind,
    ItemIconKey,
    ItemRarity,
)

from world.skills.equipment import EquipmentSlot

ROWS: tuple[ItemDefinition, ...] = (
        ItemDefinition(
            key="meal",
            display_name_zh="普通餐食",
            price_table_key="meal",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="供旅人充飢的普通餐食。",
            ),
        ),
        ItemDefinition(
            key="healing_potion",
            display_name_zh="治療藥水",
            price_table_key="potion",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.RARE,
                summary_zh="盛裝於小瓶中的治療藥水。",
            ),
            use_mechanics=ItemUseMechanics(
                consumable=True,
                combat_allowed=True,
            ),
        ),
        ItemDefinition(
            key="plain_sword",
            display_name_zh="普通劍",
            price_table_key="plain_sword",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.COMMON,
                summary_zh="鍛鐵打造的普通劍。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.PLAIN_SWORD,
        ),
        ItemDefinition(
            key="iron_dagger",
            display_name_zh="鐵短刀",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.COMMON,
                summary_zh="王國鍛坊量產的輕便副手短刀。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_OFF,
            modifier_key=EquipmentModifierKey.IRON_DAGGER,
        ),
        ItemDefinition(
            key="hunting_throwing_axe",
            display_name_zh="狩獵擲斧",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.COMMON,
                summary_zh="獸王國獵手常用的短柄擲斧。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_OFF,
            modifier_key=EquipmentModifierKey.HUNTING_THROWING_AXE,
        ),
        ItemDefinition(
            key="hunters_longbow",
            display_name_zh="獵手長弓",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="獸王國獸材層壓製成的獵用長弓。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.HUNTERS_LONGBOW,
        ),
        ItemDefinition(
            key="apprentice_focus_staff",
            display_name_zh="見習術師法杖",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOOL,
                icon_key=ItemIconKey.TOOL,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="帝國魔法學院見習生使用的導魔長杖。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.APPRENTICE_FOCUS_STAFF,
        ),
        ItemDefinition(
            key="knight_blade",
            display_name_zh="騎士制式長劍",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="王國騎士團制式長劍，鍛造紮實。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.KNIGHT_BLADE,
        ),
        ItemDefinition(
            key="wooden_club",
            display_name_zh="木製棍棒",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.COMMON,
                summary_zh="農具房改製的堅硬木製棍棒。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.WOODEN_CLUB,
        ),
        ItemDefinition(
            key="gilded_saber",
            display_name_zh="鍍金軍刀",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="貴族隨身佩戴的鍍金細軍刀。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.GILDED_SABER,
        ),
        ItemDefinition(
            key="great_axe",
            display_name_zh="雙手巨斧",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="獸人戰士慣用的沉重雙手巨斧。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.GREAT_AXE,
        ),
        ItemDefinition(
            key="ashen_scimitar",
            display_name_zh="灰燼彎刀",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="精靈鍛於餘燼之火的彎刀。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.ASHEN_SCIMITAR,
        ),
        ItemDefinition(
            key="steel_fang_dagger",
            display_name_zh="鋼牙短刀",
            price_table_key="mundane_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="獸人獵手慣用的銳利主手短刀。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.STEEL_FANG_DAGGER,
        ),
        ItemDefinition(
            key="magic_sword",
            display_name_zh="魔導長劍",
            price_table_key="magic_weapon",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.WEAPON,
                icon_key=ItemIconKey.WEAPON,
                rarity=ItemRarity.EPIC,
                summary_zh="附魔師傅導入元素精萃的魔導劍。",
            ),
            equipment_slot=EquipmentSlot.WEAPON_MAIN,
            modifier_key=EquipmentModifierKey.MAGIC_SWORD,
        ),
)
