"""Registry data slice: the inspect-only lore codex roster (foods, potions, tools, materials, curios).

Moved verbatim from the ``ITEM_REGISTRY`` literal in
``world/lore/items.py``; ``ROWS`` is the contiguous, in-order
entry block (section comments included) the assembly concatenates.
Do not reorder or edit rows here: registry order is observable.
"""

from world.lore.items.vocab import (
    ItemPresentation,
    ItemDefinition,
    ItemKind,
    ItemIconKey,
    ItemRarity,
)

ROWS: tuple[ItemDefinition, ...] = (
        # Inspect-only lore codex items: 6 Foods (land-lore-inspect-only-items D2)
        ItemDefinition(
            key="kingdom_rye_hardtack",
            display_name_zh="王國黑麥硬麵包",
            price_table_key="meal",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="礦工下坑必帶的黑麥硬麵包，耐嚼且扛餓。",
            ),
        ),
        ItemDefinition(
            key="adventurer_field_ration",
            display_name_zh="冒險者攜行口糧",
            price_table_key="meal",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="公會統一配發的壓縮口糧，D 級以下常見裝備。",
            ),
        ),
        ItemDefinition(
            key="imperial_candied_fruit",
            display_name_zh="帝國蜜漬果乾",
            price_table_key="specialty_food",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="東南港口特產的蜜漬水果乾，耐放又香甜。",
            ),
        ),
        ItemDefinition(
            key="beastfolk_smoked_jerky",
            display_name_zh="獸王國燻獸肉乾",
            price_table_key="specialty_food",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="高地獵手以獵物燻製而成的肉乾，蛋白質豐富。",
            ),
        ),
        ItemDefinition(
            key="harbor_lobster_bisque",
            display_name_zh="東南港灣龍蝦濃湯",
            price_table_key="specialty_food",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.COMMON,
                summary_zh="港口城市貴族餐廳的招牌濃湯，滋味濃郁。",
            ),
        ),
        ItemDefinition(
            key="elven_candied_blossom",
            display_name_zh="精靈蜜漬花蕊",
            price_table_key="specialty_food",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.FOOD,
                icon_key=ItemIconKey.FOOD,
                rarity=ItemRarity.RARE,
                summary_zh="精靈少量流出人類社會的花蕊蜜餞，甜而不膩。",
            ),
        ),
        # Inspect-only lore codex items: 5 Remedies
        ItemDefinition(
            key="miners_bracing_broth",
            display_name_zh="王國礦工提神湯",
            price_table_key="potion",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.COMMON,
                summary_zh="礦工下坑前灌下的辛辣提神湯，效果全憑意志力。",
            ),
        ),
        ItemDefinition(
            key="beastfolk_herbal_salve",
            display_name_zh="獸王國藥草膏",
            price_table_key="potion",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.COMMON,
                summary_zh="部族薩滿以高地藥草熬製的敷膏，外用居多。",
            ),
        ),
        ItemDefinition(
            key="passion_draught",
            display_name_zh="迷情藥",
            price_table_key="potion",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="黑市流傳的催情酊劑，〔飾品〕迷情絲頸環便是浸過這類藥劑製成；效力溫和，可被意志壓制。",
            ),
        ),
        ItemDefinition(
            key="spirit_dew",
            display_name_zh="靈露",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.EPIC,
                summary_zh="以鮮活精靈體液為藥引低溫蒸餾出的金色藥劑，以極強的催情效力聞名，傳聞飲下者會在高潮般的熱浪中親眼看著自己的傷口合攏。",
            ),
        ),
        ItemDefinition(
            key="elven_tear",
            display_name_zh="精靈之淚",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.POTION,
                icon_key=ItemIconKey.POTION,
                rarity=ItemRarity.EPIC,
                summary_zh="精靈情緒激動時分泌的稀罕淚珠，鍊金師視為頂級藥引。",
            ),
        ),
        # Inspect-only lore codex items: 4 Tools
        ItemDefinition(
            key="enchanted_compass",
            display_name_zh="附魔羅盤",
            price_table_key="tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOOL,
                icon_key=ItemIconKey.TOOL,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="內嵌小型魔力晶片的羅盤，在迷宮中仍能指出「地表方向」。",
            ),
        ),
        ItemDefinition(
            key="dungeon_flare_talisman",
            display_name_zh="迷宮探照符",
            price_table_key="tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOOL,
                icon_key=ItemIconKey.TOOL,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="一次性符紙，撕開後照亮周遭一小段時間，深層迷宮探索必備。",
            ),
        ),
        ItemDefinition(
            key="beastfolk_signal_conch",
            display_name_zh="通訊法螺",
            price_table_key="tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOOL,
                icon_key=ItemIconKey.TOOL,
                rarity=ItemRarity.RARE,
                summary_zh="灌注風屬性魔力後可傳遞短距離語音的巨型海螺。",
            ),
        ),
        ItemDefinition(
            key="camp_ward_kit",
            display_name_zh="露營魔導具",
            price_table_key="tool",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.TOOL,
                icon_key=ItemIconKey.TOOL,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="展開後形成小型結界帳篷，隔絕野外的風雨與蟲獸。",
            ),
        ),
        # Inspect-only lore codex items: 6 Materials
        ItemDefinition(
            key="goblin_ear",
            display_name_zh="哥布林耳朵",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.COMMON,
                summary_zh="公會討伐任務常見的證明物，一對耳朵換一份微薄報酬。",
            ),
        ),
        ItemDefinition(
            key="slime_residue",
            display_name_zh="史萊姆黏液",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.COMMON,
                summary_zh="黏稠且帶弱酸性的史萊姆殘留物，煉金坊常見原料。",
            ),
        ),
        ItemDefinition(
            key="earth_drake_scale",
            display_name_zh="地龍鱗片",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.RARE,
                summary_zh="地龍蛻下或討伐後取得的鱗片，質地堅硬耐熱。",
            ),
        ),
        ItemDefinition(
            key="troll_fang",
            display_name_zh="巨魔尖牙",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.EPIC,
                summary_zh="高階魔獸巨魔的犬齒，質地近乎精鋼。",
            ),
        ),
        ItemDefinition(
            key="elven_essence",
            display_name_zh="精靈體液",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.EPIC,
                summary_zh="以鎖魔玻璃瓶封存的鮮活精靈體液，蘊含強大魔力與極強催情效力的液態素材；生命力一旦消散就淪為凡液，只有具備保鮮手段的鍊金師敢經手，視為珍寶。",
            ),
        ),
        ItemDefinition(
            key="ancient_dragon_heart",
            display_name_zh="古龍心臟",
            price_table_key="material",
            sellable=True,
            presentation=ItemPresentation(
                kind=ItemKind.MATERIAL,
                icon_key=ItemIconKey.MATERIAL,
                rarity=ItemRarity.LEGENDARY,
                summary_zh="傳說中古龍的心臟，據信是製作神代等級魔法道具的唯一材料，全大陸未有交易紀錄。",
            ),
        ),
        # Inspect-only lore codex items: 3 Curios
        ItemDefinition(
            key="family_crest_token",
            display_name_zh="家族信物",
            price_table_key="relic",
            sellable=False,
            presentation=ItemPresentation(
                kind=ItemKind.MISC,
                icon_key=ItemIconKey.MISC,
                rarity=ItemRarity.UNCOMMON,
                summary_zh="由家族長輩傳下、刻有家紋或圖騰的小型物件，通常是任務或劇情的身分線索。",
            ),
        ),
        ItemDefinition(
            key="ancient_mystery_key",
            display_name_zh="謎樣的古老鑰匙",
            price_table_key="relic",
            sellable=False,
            presentation=ItemPresentation(
                kind=ItemKind.MISC,
                icon_key=ItemIconKey.MISC,
                rarity=ItemRarity.RARE,
                summary_zh="造型古樸、無法辨識鎖孔用途的鑰匙，據信與某座已知或未知的迷宮有關。",
            ),
        ),
        ItemDefinition(
            key="elven_child_toy",
            display_name_zh="精靈的簡陋玩具",
            price_table_key="relic",
            sellable=False,
            presentation=ItemPresentation(
                kind=ItemKind.MISC,
                icon_key=ItemIconKey.MISC,
                rarity=ItemRarity.COMMON,
                summary_zh="精靈孩童隨手製作的簡陋玩具，若被外人拾獲，通常代表附近有精靈幼體活動——世界觀提醒：精靈幼體對其他種族十分危險，因為他們不擅控制力道、不分是非。",
            ),
        ),
)
