"""關係線 (partner line): partner acts and the D-12 opposite-sex branch.

Ships the two seed acts this change registers; the sexual-catalog-partner
proposal appends the remaining acts to this same tuple and owns no other
file. 交合/深度交合 (vaginal intercourse and the D-12 ``virgin``-breaking
branch) are deferred by design.md D-2: ``SexualActDef.sexual_events`` is a
fixed tuple with no mechanism to select an event from participant state.
"""

from world.skills.registry import SkillDef, TargetSpec
from world.skills.sexual_acts._builder import SexualActDef, _act_family

PARTNER_ACTS: tuple[tuple[SkillDef, SexualActDef], ...] = _act_family(
    "關係",
    (
        "partner_caress",
        "愛撫",
        "以溫柔的撫摸回應對方的身體，在肌膚相觸間拉近彼此的距離。",
        TargetSpec.SINGLE,
        {},
        10,
        "腰腹",
        "腰腹",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_hand_hold",
        "牽手交纏",
        "十指交纏地牽起對方的手，讓曖昧在掌心之間蔓延。",
        TargetSpec.SINGLE,
        {},
        3,
        "腰腹",
        "腰腹",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_kiss",
        "親吻",
        "輕輕吻上對方的雙唇，在唇舌交纏之間傳遞無聲的渴望。",
        TargetSpec.SINGLE,
        {"duo_act_count": 5},
        12,
        "口唇",
        "口唇",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_neck_caress",
        "撫摸頸項",
        "以指尖沿著頸項細細撫過，感受對方肌膚的顫慄與溫熱。",
        TargetSpec.SINGLE,
        {"duo_act_count": 5},
        12,
        "頸項",
        "頸項",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_breast_play",
        "揉捏胸部",
        "隔著衣物揉捏對方的胸部，讓揉弄的力道激起陣陣酥麻。",
        TargetSpec.SINGLE,
        {"duo_act_count": 5},
        13,
        "乳房",
        "乳房",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_ear_whisper",
        "耳邊細語",
        "湊近耳邊低聲細語，溫熱的吐息讓對方的耳根發燙。",
        TargetSpec.SINGLE,
        {"duo_act_count": 5},
        11,
        "耳朵",
        "耳朵",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_deep_caress",
        "深度愛撫",
        "探向對方腿間，以指尖細膩地愛撫私處，引出濕潤的顫動。",
        TargetSpec.SINGLE,
        {"duo_act_count": 15},
        20,
        "私處",
        "私處",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_oral_service",
        "口舌服務",
        "俯身以口舌溫柔地服侍對方，用舌尖細細品嘗每一寸敏感。",
        TargetSpec.SINGLE,
        {"duo_act_count": 15},
        19,
        "口唇",
        "口唇",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_breast_sex",
        "乳交",
        "將對方的乳房貼在胸前搓揉磨蹭，讓柔軟的觸感包裹住慾望。",
        TargetSpec.SINGLE,
        {"duo_act_count": 15},
        19,
        "乳房",
        "乳房",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        ("breast_sex_performed",),
        True,
    ),
    (
        "partner_thigh_rub",
        "腿間摩擦",
        "以腿根貼著對方的大腿來回摩擦，在若即若離之間撩撥慾火。",
        TargetSpec.SINGLE,
        {"duo_act_count": 15},
        18,
        "大腿",
        "大腿",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_foot_service",
        "足部服務",
        "捧起對方的腳，以指尖與唇舌細細服侍足部，帶來陣陣酥癢。",
        TargetSpec.SINGLE,
        {"duo_act_count": 15},
        17,
        "足部",
        "足部",
        0.5,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_anal_sex",
        "後庭交合",
        "從後方緩緩進入對方的後庭，在緊緻的包覆之中深深挺入。",
        TargetSpec.SINGLE,
        {"duo_act_count": 30, "climax_count": 10},
        26,
        "後庭",
        "後庭",
        0.6,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_mutual_masturbation",
        "相互自慰",
        "與對方相對而坐，彼此撫慰對方腿間的敏感處，共享同樣的節奏。",
        TargetSpec.SINGLE,
        {"duo_act_count": 30, "climax_count": 10},
        18,
        "私處",
        "私處",
        1.0,
        ("duo_act_count",),
        ("duo_act_count",),
        (),
        True,
    ),
    (
        "partner_group_caress",
        "多人愛撫",
        "同時愛撫在場的每一個人，讓指尖在腰腹與肌膚之間游走。",
        TargetSpec.AREA,
        {"duo_act_count": 30},
        18,
        None,
        "腰腹",
        0.5,
        ("group_act_count",),
        ("group_act_count",),
        (),
        True,
    ),
    (
        "partner_group_orgy",
        "多人交歡",
        "與在場的眾人交纏在一起，在肢體交疊之間縱情享樂。",
        TargetSpec.AREA,
        {"group_act_count": 15},
        20,
        None,
        "腰腹",
        0.5,
        ("group_act_count",),
        ("group_act_count",),
        (),
        True,
    ),
    (
        "partner_group_service",
        "群體服務",
        "輪流以身體服侍在場的每一個人，讓眾人的慾望都得到滿足。",
        TargetSpec.AREA,
        {"group_act_count": 30},
        22,
        None,
        "腰腹",
        0.5,
        ("group_act_count",),
        ("group_act_count",),
        (),
        True,
    ),
)
