"""羞恥線 (shame line): exposure- and shame-driven acts.

The one unconditionally-owned seed act 撩起衣襬 plus nine counter-gated acts
across four tiers: three at ``exposure_act_count >= 5``, two at
``exposure_act_count >= 20`` (公開自慰 compound-gated on
``masturbation_count``), two at ``watched_count >= 10`` (公開表演
compound-gated on ``exposure_act_count``), and two at
``exposure_act_count >= 50`` (無恥宣言 compound-gated on ``watched_count``).
Every act except the battlefield taunt 挑釁凝視 reuses the ``self_exposure``
event shipped with the seed — no further rulebook row is needed.
"""

from world.skills.registry import SkillDef, TargetSpec
from world.skills.sexual_acts._builder import SexualActDef, _act_family

SHAME_ACTS: tuple[tuple[SkillDef, SexualActDef], ...] = _act_family(
    "羞恥",
    (
        "shame_hem_lift",
        "撩起衣襬",
        "撩起自己的衣襬，讓肌膚在他人目光下微微裸露。",
        TargetSpec.SELF,
        {},
        6,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
    (
        "shame_half_expose_chest",
        "半露出·胸口",
        "拉下衣領露出胸口，讓肌膚在半掩之間引人注目。",
        TargetSpec.SELF,
        {"exposure_act_count": 5},
        9,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
    (
        "shame_half_expose_lower",
        "半露出·下身",
        "掀起裙擺露出下身，在他人目光下微微發顫。",
        TargetSpec.SELF,
        {"exposure_act_count": 5},
        9,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
    (
        "shame_loosen_collar",
        "解開衣襟",
        "解開衣襟的扣子，讓胸前的風光若隱若現。",
        TargetSpec.SELF,
        {"exposure_act_count": 5},
        8,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
    (
        "shame_full_expose",
        "全露出",
        "褪去所有遮掩，將身體全然暴露在他人眼前。",
        TargetSpec.SELF,
        {"exposure_act_count": 20},
        16,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
    (
        "shame_public_masturbation",
        "公開自慰",
        "在眾人目光下撫弄自己，讓羞恥與快感一同攀升。",
        TargetSpec.SELF,
        {"exposure_act_count": 20, "masturbation_count": 25},
        18,
        None,
        None,
        1.0,
        ("exposure_act_count", "masturbation_count", "watched_count"),
        (),
        ("self_exposure", "masturbation_climax"),
        False,
    ),
    (
        "shame_provocative_gaze",
        "挑釁凝視",
        "以充滿挑逗的目光凝視敵人，令對方的心神在戰場上搖曳。",
        TargetSpec.AREA,
        {"watched_count": 10},
        14,
        None,
        "腰腹",
        0.4,
        ("hostile_act_count",),
        (),
        (),
        True,
    ),
    (
        "shame_public_performance",
        "公開表演",
        "在眾人面前進行一場露骨的表演，用身體吸引所有的目光。",
        TargetSpec.AREA,
        {"watched_count": 10, "exposure_act_count": 20},
        15,
        None,
        "腰腹",
        0.6,
        ("watched_count", "exposure_act_count"),
        (),
        ("self_exposure",),
        True,
    ),
    (
        "shame_devoted_pose",
        "獻身姿態",
        "擺出將自己獻給所有人的姿態，徹底放棄遮掩與抵抗。",
        TargetSpec.AREA,
        {"exposure_act_count": 50},
        22,
        None,
        "腰腹",
        0.5,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        True,
    ),
    (
        "shame_shameless_declaration",
        "無恥宣言",
        "大聲宣言自己的無恥，將羞恥本身化為快感。",
        TargetSpec.SELF,
        {"exposure_act_count": 50, "watched_count": 30},
        20,
        None,
        None,
        1.0,
        ("exposure_act_count",),
        (),
        ("self_exposure",),
        False,
    ),
)
