"""獨處線 (solo line): solo acts.

Three unconditionally-owned seed acts plus eleven counter-gated acts across
three tiers: five at ``masturbation_count >= 10``, three toy acts at
``masturbation_count >= 25``, and three advanced-toy acts at the compound
``masturbation_count >= 25`` + ``toy_use_count >= 15`` gate. Every toy act
credits both counters on cast — a toy act is still a solo act.
"""

from world.skills.registry import SkillDef, TargetSpec
from world.skills.sexual_acts._builder import SexualActDef, _act_family

SOLO_ACTS: tuple[tuple[SkillDef, SexualActDef], ...] = _act_family(
    "獨處",
    (
        "solo_self_touch",
        "自撫",
        "獨處時撫弄自己的私處，讓身體在快感中逐漸甦醒。",
        TargetSpec.SELF,
        {},
        12,
        "私處",
        None,
        1.0,
        ("masturbation_count",),
        (),
        ("masturbation_climax",),
        False,
    ),
    (
        "solo_fondle_breasts",
        "揉捏胸部",
        "隔著衣物或直接揉弄自己的乳房，享受肌膚的觸感。",
        TargetSpec.SELF,
        {},
        9,
        "乳房",
        None,
        1.0,
        ("masturbation_count",),
        (),
        (),
        False,
    ),
    (
        "solo_thigh_rub",
        "摩擦大腿",
        "夾緊雙腿來回摩擦，以隱晦的方式安撫逐漸升溫的身體。",
        TargetSpec.SELF,
        {},
        8,
        "大腿",
        None,
        1.0,
        ("masturbation_count",),
        (),
        (),
        False,
    ),
    (
        "solo_deep_touch",
        "深度自慰",
        "比自撫更深入、更專注地撫弄自己的私處，一步步推向快感的頂點。",
        TargetSpec.SELF,
        {"masturbation_count": 10},
        16,
        "私處",
        None,
        1.0,
        ("masturbation_count",),
        (),
        ("masturbation_climax",),
        False,
    ),
    (
        "solo_both_hands",
        "雙手併用",
        "雙手同時撫弄乳房與私處，讓快感在全身堆疊、攀向高潮。",
        TargetSpec.SELF,
        {"masturbation_count": 10},
        17,
        "私處",
        None,
        1.0,
        ("masturbation_count",),
        (),
        ("masturbation_climax",),
        False,
    ),
    (
        "solo_finger_lick",
        "舔舐指尖",
        "將指尖放入口中舔舐，讓唇舌與手指一同感受細微的酥麻。",
        TargetSpec.SELF,
        {"masturbation_count": 10},
        10,
        "口唇",
        None,
        1.0,
        ("masturbation_count",),
        (),
        (),
        False,
    ),
    (
        "solo_rear_touch",
        "撫弄後庭",
        "試探性地撫弄自己的後庭，在羞恥與快感之間游移。",
        TargetSpec.SELF,
        {"masturbation_count": 10},
        13,
        "後庭",
        None,
        1.0,
        ("masturbation_count",),
        (),
        (),
        False,
    ),
    (
        "solo_nipple_play",
        "玩弄乳尖",
        "揉弄自己挺立的乳尖，讓敏感的頂端在指尖下顫動。",
        TargetSpec.SELF,
        {"masturbation_count": 10},
        12,
        "乳房",
        None,
        1.0,
        ("masturbation_count",),
        (),
        (),
        False,
    ),
    (
        "solo_toy_vibrator",
        "玩具自慰·振動",
        "以振動玩具抵住私處，讓機械的顫動取代手指的節奏。",
        TargetSpec.SELF,
        {"masturbation_count": 25},
        20,
        "私處",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
    (
        "solo_toy_clamps",
        "玩具自慰·夾具",
        "用夾具夾住自己的乳尖，在輕微的刺痛與快感之間尋求平衡。",
        TargetSpec.SELF,
        {"masturbation_count": 25},
        18,
        "乳房",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
    (
        "solo_toy_plug",
        "玩具自慰·填充",
        "將玩具緩緩推入後庭，讓被填滿的壓迫感轉化為快感。",
        TargetSpec.SELF,
        {"masturbation_count": 25},
        19,
        "後庭",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
    (
        "solo_toy_advanced_link",
        "高階玩具·連結",
        "以連結玩具同時刺激身體多處要害，讓每一處都無法逃開快感。",
        TargetSpec.SELF,
        {"masturbation_count": 25, "toy_use_count": 15},
        24,
        "私處",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
    (
        "solo_toy_advanced_full",
        "高階玩具·全身",
        "讓高階玩具覆蓋全身的敏感帶，徹底沉溺在持續的刺激之中。",
        TargetSpec.SELF,
        {"masturbation_count": 25, "toy_use_count": 15},
        26,
        "私處",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
    (
        "solo_bound_masturbation",
        "拘束自慰",
        "將自己縛住後撫弄私處，在無處可逃的狀態下細細品嘗快感。",
        TargetSpec.SELF,
        {"masturbation_count": 25, "toy_use_count": 15},
        25,
        "私處",
        None,
        1.0,
        ("masturbation_count", "toy_use_count"),
        (),
        (),
        False,
    ),
)
