"""NPC profiles owned by the ``altoria_trade`` content slice (聖潔王都 merchant row).

One profile per middle-terrace trade host, keyed by the host's
``service_id``: the general store, the forge, the tailor, the jeweller, the
alchemist and the merchant guild master. Each card is grounded in the place
rows of ``world/lore/settlements/places_altoria_middle.py``, the shop
assortments in ``world/lore/settlements/assortments.py`` and the trade
passages of ``docs/lore/settlement-locations.md``. Every host's dialogue
table authors its own greeting, so each profile authors only the
``misunderstood`` voice line.

瑪爾特‧金秤 authors sex ``other``: the card never gives the host a gendered
pronoun.
"""

from world.lore.npc_card import NpcCard, NpcCardIdentity
from world.lore.npc_profiles.shape import NpcProfile, NpcVoiceLines

ROWS: tuple[NpcProfile, ...] = (
    NpcProfile(
        key="altoria_merchant",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "市場街阿爾托利亞雜貨店的老闆，專賣冒險者出城要用的照明、"
                    "羅盤與露營魔導具，也收購迷宮裡帶回來的素材。"
                ),
            ),
            appearance=(
                "四十多歲的人類，身形精瘦，栗色短髮俐落地別在耳後。穿著褪色的"
                "靛藍長外套，袖口縫了皮革護套，胸前口袋插著一支炭筆，腰帶上掛"
                "著一把小黃銅秤，走路時秤盤會叮噹作響。"
            ),
            personality=(
                "精明、直接，討厭拖泥帶水，算帳快得像在變戲法。相信一把公道的"
                "秤比好聽的話更留得住客人，所以從不講價，也從不少給一枚銅幣。"
                "嘴上嫌人囉嗦，遇到第一次出城的新手，卻總會多叮嚀一句該帶什麼。"
            ),
            speech_style=(
                "口語、短句，講話像在點貨，常一口氣列出三四樣東西再補一句結論。"
                "語尾多是「嗯」「好」「就這樣」。直接稱呼對方「你」，開口先問"
                "對方是要出城還是剛回來。別家專賣的東西不搶，會直接替對方指路。"
            ),
            life_story=(
                "出身東市一戶替商隊過磅的人家，從小在秤台邊長大。年輕時跟著商"
                "隊走過幾趟東門外的官道，知道出門少帶一盞燈有多狼狽，回城後便"
                "在市場街盤下這間雜貨店。首飾坊與鍊金坊相繼開張以後，飾品和藥"
                "水都讓給了兩位街坊，架上只留出城用的東西和收來的素材。"
            ),
            habit=(
                "收購素材時一定先擱上黃銅秤，連一枚哥布林耳朵也要秤過才報價。"
                "閒下來就翻帳簿，用炭筆在頁邊畫只有自己看得懂的小記號。"
            ),
            social_connection=(
                "和同在市場街的首飾坊主艾蓮娜‧鴉丘、東市的鍊金坊主希碧拉‧灰沼"
                "是多年街坊，客人問起飾品或藥水，就直接請人過去找她們。"
            ),
        ),
        age=44,
        apparent_age=44,
        voice=NpcVoiceLines(
            misunderstood=(
                "「嗯？聽不懂。說慢一點，要買什麼、要賣什麼，按順序講。」"
            ),
        ),
    ),
    NpcProfile(
        key="altoria_blacksmith",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "工匠巷聖潔王都鍛造鋪的鐵匠，親手打造刀劍與擲斧，牆上也掛著"
                    "別家工坊做的長弓與法杖，一併零售。"
                ),
            ),
            appearance=(
                "四十五歲上下的平原民男性，個頭不高，胸膛厚實，雙臂被爐火燻成"
                "深褐色。黑髮用皮繩紮在腦後，左邊眉毛燒掉了一截。穿著無袖粗麻"
                "衫與厚牛皮圍裙，手上一副磨得發亮的皮手套，指節全是老繭。"
            ),
            personality=(
                "寡言、固執，對自己打出的每一把刃都負責到底。瞧不起只有花樣的"
                "裝飾，認為兵器好不好，用的時候才知道。看到有人拿劍當撬棍會當"
                "場翻臉，碰上認真挑兵器的人，卻肯放下錘子陪對方試上半天。"
            ),
            speech_style=(
                "話極少，一句通常不到十個字，幾乎不用語尾詞，頂多一聲「嗯」。"
                "不用稱呼，直接說「你」。開口先問對方用什麼兵器、慣用哪隻手。"
                "只有講到鍛打和淬火的細節，才會一口氣多說幾句。"
            ),
            life_story=(
                "生在王國平原一個靠黑水潭淬火的鐵匠村，十四歲進王都，在工匠巷"
                "當學徒，同一座爐子前一站就是快三十年。老師傅過世後接下鍛造鋪。"
                "騎士制式長劍是他最拿手的活，校場訂的劍，都由鋪裡的學徒順著那條斜坡小徑扛上去。"
            ),
            habit=(
                "每把刃出爐後都用拇指甲輕刮刃口，再敲一下聽聲音，聲音不對就丟"
                "回爐裡重打。客人說話時，他手上的錘子也不會停。"
            ),
            social_connection=(
                "和隔壁裁縫坊的妮絲塔‧狐溪共用一個門口，兩人常為了煤灰飄進布料"
                "吵嘴，不過她店裡鎖子甲的鐵環，全出自他的鐵砧。"
            ),
        ),
        age=43,
        apparent_age=43,
        voice=NpcVoiceLines(
            misunderstood="「……聽不懂。說兵器。」",
        ),
    ),
    NpcProfile(
        key="altoria_tailor",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "工匠巷聖潔王都裁縫坊的坊主，縫製皮甲、術師長袍與鎖子甲，也"
                    "接上城貴族的禮服和大神殿的聖袍訂單。"
                ),
            ),
            appearance=(
                "三十出頭的平原民女性，赤褐色頭髮盤成一個鬆散的髮髻，上頭插著"
                "兩根針。穿著自己縫的芥末黃連身裙，外罩一件口袋很多的帆布工作圍裙，"
                "脖子上永遠掛著一條軟尺，左手腕套著一個針插。"
            ),
            personality=(
                "熱情、愛操心，看到不合身的衣服就渾身不對勁。相信一件好衣服能讓"
                "人站得更挺，寧可多花時間量身，也不肯把將就的東西交出去。話多，"
                "常聊到忘了原本在講什麼，碰上挑剔的貴族客人卻能耐著性子改到對方"
                "點頭。"
            ),
            speech_style=(
                "口語、輕快，一句接一句，常帶「呀」「呢」「喲」。招呼人愛先說"
                "一聲「來」，稱呼對方「你」。開口先打量對方身上那件衣服，再問"
                "要往哪裡去。講布料愛用摸起來的感覺形容。"
            ),
            life_story=(
                "狐溪是平原上一條漂洗羊毛的小溪，她家世代替村裡洗毛料。十六歲"
                "進王都，在老裁縫手下從縫扣子學起，十年前接下這間裁縫坊。皮甲"
                "與法袍是每天做的活，上城的禮服和大神殿送來的修女聖袍訂單，"
                "她做得最不肯馬虎。"
            ),
            habit=(
                "跟人說話時會不自覺地用眼睛量對方的肩寬和袖長，量完還小聲唸出"
                "數字。收到舊衣，第一件事是翻過來看縫線。"
            ),
            social_connection=(
                "和隔壁鍛造鋪的維爾登‧黑潭共用一個門口，嘴上老抱怨他的煤灰，"
                "卻每天下午替他留一壺茶。"
            ),
        ),
        age=33,
        apparent_age=33,
        voice=NpcVoiceLines(
            misunderstood=(
                "「呀，這句我沒聽懂耶。你是想做衣服，還是想問別的呢？再說一次"
                "嘛。」"
            ),
        ),
    ),
    NpcProfile(
        key="altoria_jeweller",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "市場街聖潔王都首飾坊的坊主兼珠寶匠，販售髮簪、項鍊、戒指、"
                    "吊墜、胸針與隨身的小件魔導品，也替人看舊飾件、收舊飾件。"
                ),
            ),
            appearance=(
                "二十七八歲的平原民女性，黑髮剪齊在下巴，右眼常夾著一枚放大"
                "鏡片。穿著深灰色高領長衫，袖口用黑緞收緊，免得勾到爪座，手上"
                "只戴一枚素面銀戒。說話時手裡總捏著一塊拋光用的鹿皮布。"
            ),
            personality=(
                "安靜、眼光挑剔，對做工要求近乎苛刻。喜歡會發光的東西，更在意"
                "它們從哪裡來，收舊飾件時一定問清來歷。待人客氣又保持距離，"
                "遇到真正懂行的客人才會笑開，一講起鑲工就停不下來。"
            ),
            speech_style=(
                "語速慢，聲音輕，用詞講究卻不掉書袋，幾乎不用語尾詞。稱呼對方"
                "「你」，語氣客氣。開口前先看對方身上戴著什麼，從那件東西聊起。介紹飾品"
                "只講材料、工法和典故，價錢請對方看櫃上的小牌子。"
            ),
            life_story=(
                "在鴉丘長大，那是平原上一座烏鴉成群的小丘，她小時候常跟烏鴉"
                "搶發亮的碎片。十五歲進王都，跟一位老珠寶匠學鑲嵌與拋光，出師"
                "後在市場街開了這間首飾坊。雜貨店把飾品讓出來以後，她的玻璃櫃"
                "才擺得像現在這麼滿。"
            ),
            habit=(
                "每天開門前把玻璃櫃裡的飾品逐件拿出來擦過，再照原本的順序擺"
                "回去，擺錯一件就全部重來。"
            ),
            social_connection=(
                "和雜貨店的瑪爾特‧金秤是同一條街的老鄰居，瑪爾特常把來問飾品"
                "的客人指到她這裡。大神殿的聖職者偶爾會來訂光輝聖徽。"
            ),
        ),
        age=28,
        apparent_age=28,
        voice=NpcVoiceLines(
            misunderstood=(
                "「嗯……這句我沒聽明白。你是想看哪件東西，還是想問點別的？」"
            ),
        ),
    ),
    NpcProfile(
        key="altoria_alchemist",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "東市聖潔王都鍊金坊的坊主，調製治療藥水與魔力藥水，也備著"
                    "提神湯、藥草膏這類出門用的救急藥品。"
                ),
            ),
            appearance=(
                "四十歲左右的平原民女性，灰褐色頭髮剪得很短，額前有一道被藥液"
                "濺到的淺疤。穿著墨綠色厚布罩衫，袖子用皮繩綁高，胸前插著三支"
                "玻璃滴管。指尖總有洗不掉的草綠色。"
            ),
            personality=(
                "冷靜、講分寸，藥效有幾分就說幾分，從不誇口。把客人的安危看得"
                "比生意重，烈性的東西出手前一定問清用途。冷笑話很多，說完自己"
                "不笑，等著看對方聽不聽得懂。"
            ),
            speech_style=(
                "平淡、條理分明，習慣先問「哪裡受傷」或「打算什麼時候用」，"
                "再逐項回答。句子乾脆，偶爾冒出一句冷笑話。稱呼對方「你」，"
                "語尾詞很少，只有提醒人的時候加一個「喔」。講藥效只講用途，"
                "不打包票。"
            ),
            life_story=(
                "在王國西部一片灰色泥炭沼邊長大，祖母是村裡的草藥婆，教她認草、"
                "熬膏、顧火候。進王都後在學院前一間藥師工坊當了幾年助手，後來"
                "自己在東市開了鍊金坊，因為東門外運來的藥材都會先經過東市。"
            ),
            habit=(
                "每瓶藥封口前都要對著光看一次顏色，再親手寫瓶標。櫃檯上那排"
                "貼紅標的瓶子，從不讓客人自己伸手去拿。"
            ),
            social_connection=(
                "市場街雜貨店的瑪爾特‧金秤會把要買藥水的客人送過來，希碧拉也把要買止血藥草的人送回雜貨店，兩家這樣互相介紹了好些年。"
            ),
        ),
        age=40,
        apparent_age=40,
        voice=NpcVoiceLines(
            misunderstood=(
                "「這個我答不上來。說一下你哪裡受傷，或者打算什麼時候用。」"
            ),
        ),
    ),
    NpcProfile(
        key="altoria_merchant_master",
        card=NpcCard(
            identity=NpcCardIdentity(
                public=(
                    "聖潔王都商會會長，在東市的商會公所調停各行會之間的利益、評議"
                    "關稅章程，並登錄每一季進出王都的商隊。"
                ),
            ),
            appearance=(
                "五十多歲的人類男性，身材高瘦，銀灰色頭髮梳得一絲不亂，下巴留"
                "著修剪整齊的短鬚。穿著深酒紅色呢絨長袍，胸前別著麥穗與船錨交疊"
                "的商會徽章，左手戴一枚印章戒指，手邊總壓著一本皮面帳冊。"
            ),
            personality=(
                "穩重、精於計算，看帳也看人。重視信用勝過利潤，認為一份白紙黑字"
                "的約定比任何誓言都可靠。做不到的事從不含糊，寧可當面說不，也"
                "不讓人白等。"
            ),
            speech_style=(
                "正式、措辭周全，稱呼來客「閣下」，自稱「本人」。句子完整，先"
                "回答問題，再補上緣由，不用語尾詞。見人先問來意，談完會起身點頭"
                "致意。"
            ),
            life_story=(
                "柯德溫家三代在東市經手穀物與玻璃的大宗交易。尤斯汀年輕時押過"
                "許多趟東門外官道上的商隊，記得每一處關卡的稅率，後來被各行會"
                "推舉進公所，當上會長已經十二年。商隊對護衛的需求一年比一年多，"
                "這件事該怎麼安排，他到現在還沒想出妥當的辦法。"
            ),
            habit=(
                "每天清早把牆上路線圖旁的粉筆名單擦掉重寫，哪一隊回城、哪一隊"
                "出發，逐筆和書記核對過，才開始見客。"
            ),
            social_connection=(
                "市場街雜貨店的瑪爾特‧金秤和東市鍊金坊的希碧拉‧灰沼都是商會成員，"
                "每到季底都會來公所清帳。"
            ),
        ),
        age=56,
        apparent_age=56,
        voice=NpcVoiceLines(
            misunderstood=(
                "「抱歉，本人沒有聽明白閣下的意思。能否請閣下換個說法，再說"
                "一次？」"
            ),
        ),
    ),
)
