"""Equipment adjustment prose tests (P3, tasks 3.4/4.4).

Pins the exact D4 vocabulary contract: segments joined by 「｜」 in the
fixed field-declaration order, signed integers with the U+2212 minus,
percent fields as ±N%, gauge fields as <gauge>上限 ±N, immunity via
registered display labels, zero-valued numeric fields omitted.

Data-independent (migrate-rules-equipment-item-tests-off-real-data): the
formatter is exercised against DELIBERATELY CONSTRUCTED synthetic rule rows
(bound to a runtime-probed modifier key) with literal expectations written
here — never values generated by the production formatter and never shipped
rows. The shipped gear's exact prose stays pinned by the registered
data-contract file ``test_equipment_effect_rulebook.py``.
"""

from tools.spec_traceability import covers_requirement

import unittest
from dataclasses import replace
from unittest.mock import patch

from evennia.utils.create import create_object
from evennia.utils.test_resources import EvenniaTestCase

from typeclasses.characters import PlayerCharacter
from world.lore.items import EquipmentSlot
from world.rules import status_display
from world.rules.equipment_effects import (
    EquipmentEffectRule,
    equipment_adjustment_text,
    worn_item_keys,
)
from world.rules.status_display import ConditionDisplay
from world.tests.synthetic_data import make_item, synthetic_registries

from ._equipment_rulebook_probes import unique_rule, rule_for

# One borrowed rulebook row (fail-fast unique probe) provides the modifier
# key the synthetic gear binds to; its shipped values are replaced per test.
_PROBE_MODIFIER, _PROBE_RULE = unique_rule(
    "attached_buffs", lambda rule: bool(rule.attached_buffs)
)

_WARD_CODE = "t_synthetic_ward"
_WARD_LABEL = "護咒"

_EMPTY_RULE = EquipmentEffectRule(
    adjustments={}, gauge_caps={}, immune=(), attached_buffs=(), exposure_bias=0
)

_PROSE_ITEM = make_item(
    "t_glass_bulwark",
    display_name_zh="琉璃合成盾",
    price_table_key="t_ironbite_steel",
    equipment_slot=EquipmentSlot.ARMOR,
    modifier_key=_PROBE_MODIFIER,
)
_NON_EQUIPMENT = make_item("t_wick_lantern", display_name_zh="合成燭燈")
_BLADE = make_item(
    "t_worn_blade",
    display_name_zh="配戴合成刃",
    price_table_key="t_ironbite_steel",
    equipment_slot=EquipmentSlot.WEAPON_MAIN,
    modifier_key=_PROBE_MODIFIER,
)
_CHARM = make_item(
    "t_worn_charm",
    display_name_zh="配戴合成吊飾",
    equipment_slot=EquipmentSlot.ACCESSORY,
    modifier_key=_PROBE_MODIFIER,
)
_SCOPE_EXTRA = {
    "items": {
        _PROSE_ITEM.key: _PROSE_ITEM,
        _NON_EQUIPMENT.key: _NON_EQUIPMENT,
        _BLADE.key: _BLADE,
        _CHARM.key: _CHARM,
    }
}


def _patch_rule(rule: EquipmentEffectRule):
    """Swap the borrowed row's rule for one constructed here."""
    return patch.dict(
        "world.rules.equipment_effects.EQUIPMENT_EFFECT_RULES",
        {_PROBE_MODIFIER: rule},
    )


def _patch_ward_display():
    """Register display metadata for the synthetic immune code."""
    return patch.dict(
        status_display.STATUS_DISPLAY,
        {_WARD_CODE: ConditionDisplay(_WARD_CODE, _WARD_LABEL, "mild")},
    )


@synthetic_registries("items", extra=_SCOPE_EXTRA)
class EquipmentAdjustmentTextTests(unittest.TestCase):
    @covers_requirement(
        "equipment-effects::equipment-adjustments-render-as-deterministic-prose"
    )
    def test_every_layer_renders_in_the_fixed_vocabulary_order(self):
        # pleasure_gain / exposure_bias belong to P4 presentation and are
        # deliberately absent from the P3 prose vocabulary.
        rule = replace(
            _PROBE_RULE,
            adjustments={
                "pleasure_gain": "+10%",  # P4 vocabulary: must NOT render
                "atk_phys": -2,
                "defense": 8,
                "agility": "-10%",
                "magic_power": 6,
                "mp_cost": "-5%",
                "heal_gain": "+10%",
            },
            gauge_caps={"hp": 15, "mp": 7, "sp": 3},
            immune=(_WARD_CODE,),
        )
        with _patch_rule(rule), _patch_ward_display():
            self.assertEqual(
                equipment_adjustment_text(_PROSE_ITEM.key),
                "攻擊 −2｜防禦 +8｜敏捷 −10%｜魔力 +6｜施法消耗 −5%｜治療 +10%"
                "｜生命上限 +15｜法力上限 +7｜體力上限 +3｜免疫護咒",
            )

    def test_immunity_only(self):
        rule = replace(_EMPTY_RULE, immune=(_WARD_CODE,))
        with _patch_rule(rule), _patch_ward_display():
            self.assertEqual(equipment_adjustment_text(_PROSE_ITEM.key), "免疫護咒")

    def test_flat_and_percent_agility_render_their_kinds(self):
        rule = replace(
            _EMPTY_RULE,
            adjustments={"atk_phys": 2, "agility": "-5%"},
        )
        with _patch_rule(rule):
            self.assertEqual(
                equipment_adjustment_text(_PROSE_ITEM.key), "攻擊 +2｜敏捷 −5%"
            )

    def test_zero_valued_numeric_fields_are_omitted(self):
        rule = replace(
            _EMPTY_RULE,
            adjustments={"atk_phys": 0, "agility": "-0%", "defense": 3},
            gauge_caps={"hp": 0},
        )
        with _patch_rule(rule):
            self.assertEqual(equipment_adjustment_text(_PROSE_ITEM.key), "防禦 +3")

    def test_empty_entry_renders_empty(self):
        with _patch_rule(_EMPTY_RULE):
            self.assertEqual(equipment_adjustment_text(_PROSE_ITEM.key), "")

    def test_non_equipment_and_unknown_items_render_empty(self):
        self.assertEqual(equipment_adjustment_text(_NON_EQUIPMENT.key), "")
        self.assertEqual(equipment_adjustment_text("t_no_such_key"), "")


class WornItemKeysTests(unittest.TestCase):
    """Collection reads the fail-closed normalization: only registered keys
    (synthetic rows in scope) and well-formed slots collect."""

    def _entity(self, equipment):
        from types import SimpleNamespace

        return SimpleNamespace(db=SimpleNamespace(equipment=equipment))

    @synthetic_registries("items", extra=_SCOPE_EXTRA)
    def test_singletons_and_accessories_collect(self):
        entity = self._entity(
            {
                "weapon_main": _BLADE.key,
                "weapon_off": None,
                "armor": _PROSE_ITEM.key,
                "accessories": [_CHARM.key],
            }
        )
        self.assertEqual(
            worn_item_keys(entity),
            {_BLADE.key, _PROSE_ITEM.key, _CHARM.key},
        )

    def test_malformed_collects_nothing(self):
        entity = self._entity({"weapon_main": 1})
        self.assertEqual(worn_item_keys(entity), frozenset())

    def test_none_collects_nothing(self):
        from types import SimpleNamespace

        entity = SimpleNamespace(db=SimpleNamespace(equipment=None))
        self.assertEqual(worn_item_keys(entity), frozenset())


class EquipmentLookCardTests(EvenniaTestCase):
    """The shared 看 / explore.look appearance seam renders the item card."""

    def test_registry_mirror_object_renders_summary_and_prose(self):
        open_scope = synthetic_registries("items", extra=_SCOPE_EXTRA)
        open_scope.__enter__()
        self.addCleanup(open_scope.__exit__, None, None, None)
        rule = replace(_EMPTY_RULE, adjustments={"atk_phys": 4})
        entity = create_object(PlayerCharacter, key="mirror target")
        entity.race = "human"
        entity.apply_race_baseline()
        from world.rules.equipment import materialize_registry_object

        with _patch_rule(rule):
            mirror = materialize_registry_object(entity, _PROSE_ITEM.key)
            card = entity.at_look(mirror)
        self.assertIn(_PROSE_ITEM.display_name_zh, card)
        self.assertIn("攻擊 +4", card)

    def test_non_registry_object_keeps_the_plain_desc(self):
        entity = create_object(PlayerCharacter, key="plain target")
        entity.race = "human"
        entity.apply_race_baseline()
        plain = create_object("typeclasses.objects.Object", key="普通木箱")
        card = entity.at_look(plain)
        self.assertIn("普通木箱", card)


if __name__ == "__main__":
    unittest.main()
