"""Palette generator contracts (webclient-narrative-markup).

The committed ``ansi_palette.css`` is generated by a pure function; these
tests prove it cannot drift: regenerating reproduces the committed file
byte-for-byte, every class exists exactly once, every foreground entry clears
the contrast floor, and mapping preserves its numerical boundaries. Browser
motion tests cover the generated blink rule through computed styles.
"""

from __future__ import annotations

import importlib.util
import colorsys
from pathlib import Path
import re
import unittest

from tools.spec_traceability import covers_requirement

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR_PATH = REPO_ROOT / "tools" / "gen_ansi_palette.py"
CSS_PATH = REPO_ROOT / "web" / "static" / "webclient" / "css" / "ansi_palette.css"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_ansi_palette", GENERATOR_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class AnsiPaletteTest(unittest.TestCase):
    """The committed palette matches its pure generator byte-for-byte."""

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_regeneration_reproduces_the_committed_file(self):
        generator = _load_generator()
        committed = CSS_PATH.read_text(encoding="utf-8")
        self.assertEqual(
            generator.build_stylesheet(),
            committed,
            "ansi_palette.css drifted from tools/gen_ansi_palette.py; "
            "regenerate it with `uv run --locked python tools/gen_ansi_palette.py`",
        )

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_every_color_class_exists_exactly_once(self):
        generator = _load_generator()
        text = generator.build_stylesheet()
        colors = re.findall(r"^\.color-(\d{3}) \{", text, flags=re.M)
        bgcolors = re.findall(r"^\.bgcolor-(\d{3}) \{", text, flags=re.M)
        self.assertEqual(len(colors), 256)
        self.assertEqual(len(bgcolors), 256)
        self.assertEqual(len(set(colors)), 256)
        self.assertEqual(len(set(bgcolors)), 256)

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_every_foreground_entry_clears_the_contrast_floor(self):
        generator = _load_generator()
        text = generator.build_stylesheet()
        for match in re.finditer(r"^\.color-(\d{3}) \{ color: (#[0-9a-f]{6}); \}", text, flags=re.M):
            hex_value = match.group(2)
            rgb = tuple(int(hex_value[i : i + 2], 16) for i in (1, 3, 5))
            ratio = generator.contrast_ratio(rgb, generator.INK)
            self.assertGreaterEqual(
                ratio,
                3.0,
                f"color-{match.group(1)} {hex_value} clears the contrast floor",
            )

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_background_entries_are_raw_palette_values(self):
        generator = _load_generator()
        text = generator.build_stylesheet()
        for index, rgb in generator.build_palette():
            hex_value = "#{:02x}{:02x}{:02x}".format(*rgb)
            self.assertIn(
                f".bgcolor-{index:03d} {{ background-color: {hex_value}; }}",
                text,
                f"bgcolor-{index:03d} must be the raw palette value",
            )

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_final_foregrounds_have_bounded_saturation(self):
        text = _load_generator().build_stylesheet()
        for index, value in re.findall(r"^\.color-(\d{3}) \{ color: #([0-9a-f]{6}); \}", text, re.M):
            rgb = tuple(int(value[i:i + 2], 16) / 255 for i in (0, 2, 4))
            with self.subTest(index=index):
                self.assertLessEqual(colorsys.rgb_to_hls(*rgb)[2], 0.62)

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_cube_mapping_preserves_hue_and_lightness_before_flooring(self):
        generator = _load_generator()
        for index, rgb in generator.build_palette()[16:232]:
            hue, lightness, saturation = colorsys.rgb_to_hls(*(v / 255 for v in rgb))
            mapped = generator.narrative_foreground(index, rgb)
            new_hue, new_lightness, new_saturation = colorsys.rgb_to_hls(*(v / 255 for v in mapped))
            with self.subTest(index=index):
                self.assertLessEqual(new_saturation, 0.62)
                self.assertLessEqual(abs(new_lightness - lightness), 1 / 255)
                if saturation:
                    difference = abs(hue - new_hue)
                    self.assertLessEqual(min(difference, 1 - difference) * 360, 2)
                if saturation <= 0.62:
                    self.assertEqual(mapped, rgb)

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_muted_ansi_pairs_keep_brightness_order_and_gold_anchor(self):
        generator = _load_generator()
        palette = dict(generator.build_palette())
        for index in range(1, 7):
            normal = generator.narrative_foreground(index, palette[index])
            bright = generator.narrative_foreground(index + 8, palette[index + 8])
            with self.subTest(index=index):
                self.assertGreater(generator.contrast_ratio(bright, (20, 16, 25)),
                                   generator.contrast_ratio(normal, (20, 16, 25)))
                self.assertGreaterEqual(generator.contrast_ratio(normal, (20, 16, 25)), 4.5)
                self.assertNotEqual(bright, palette[index + 8])
        tokens = (REPO_ROOT / "web/webclient-app/styles/tokens.css").read_text()
        gold = re.search(r"--gold-400:\s*(#[0-9a-f]{6})", tokens).group(1)
        self.assertEqual(
            "#{:02x}{:02x}{:02x}".format(*generator.narrative_foreground(11, palette[11])),
            gold,
        )
        for index in (0, 7, 8, 15, *range(232, 256)):
            self.assertEqual(generator.narrative_foreground(index, palette[index]), palette[index])

    @covers_requirement(
        "webclient-narrative-markup::the-narrative-palette-is-generated-with-a-contrast-floor-and-honors-reduced-motion"
    )
    def test_palette_covers_the_ansi_cube_and_grayscale(self):
        generator = _load_generator()
        palette = dict(generator.build_palette())
        self.assertEqual(palette[0], (0x00, 0x00, 0x00))
        self.assertEqual(palette[9], (0xFF, 0x00, 0x00))
        self.assertEqual(palette[15], (0xFF, 0xFF, 0xFF))
        # 6x6x6 cube starts at index 16 on the standard levels.
        self.assertEqual(palette[16], (0x00, 0x00, 0x00))
        self.assertEqual(palette[17], (0x00, 0x00, 0x5F))
        self.assertEqual(palette[188], (0xD7, 0xD7, 0xD7))
        # Grayscale ramp 232..255.
        self.assertEqual(palette[232], (0x08, 0x08, 0x08))
        self.assertEqual(palette[255], (0xEE, 0xEE, 0xEE))


if __name__ == "__main__":
    unittest.main()
