"""Generate the ANSI/xterm-256 narrative palette stylesheet.

The Elosern WebClient replaced Evennia's stock ``webclient.css`` with a
project theme, which dropped the 512 ``.color-NNN``/``.bgcolor-NNN`` rules the
portal's ``parse_html`` output relies on. This pure generator reproduces that
palette deterministically:

- the 16 ANSI entries using the same RGB values Evennia's stock sheet uses,
- the 6x6x6 color cube on the standard xterm component levels
  ``0x00, 0x5f, 0x87, 0xaf, 0xd7, 0xff`` (Evennia's stock sheet has a
  long-standing ``0xdf``-instead-of-``0xd7`` quirk at level 4; the standard
  level is used here),
- the 24-step grayscale ramp.

Foreground entries use an authored muted ANSI table and a 0.62 saturation
cap for the cube, then pass through a contrast floor: while the WCAG contrast
ratio against the message band's ink reference (``#141019``) is below
3.0, the color is blended 10% toward the paper foreground (``--elm-paper``,
``#ece7db``), up to 9 steps. Background entries are emitted raw -- they are a
background, and the span's own foreground class handles legibility.

The committed ``web/static/webclient/css/ansi_palette.css`` is regenerated by
``web/webclient/tests/test_ansi_palette.py`` and byte-compared, so the
checked-in file can never drift from this generator.
"""

from __future__ import annotations

import colorsys
from math import ceil, floor
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "web/static/webclient/css/ansi_palette.css"

INK = (0x14, 0x10, 0x19)
PAPER = (0xEC, 0xE7, 0xDB)
CONTRAST_FLOOR = 3.0
BLEND_STEPS = 9

# Evennia's 16 ANSI entries, matching its stock webclient.css values.
ANSI_16 = (
    (0x00, 0x00, 0x00),  # 000 black
    (0x80, 0x00, 0x00),  # 001 red
    (0x00, 0x80, 0x00),  # 002 green
    (0x80, 0x80, 0x00),  # 003 yellow
    (0x00, 0x00, 0x80),  # 004 blue
    (0x80, 0x00, 0x80),  # 005 magenta
    (0x00, 0x80, 0x80),  # 006 cyan
    (0xC0, 0xC0, 0xC0),  # 007 white
    (0x80, 0x80, 0x80),  # 008 bright black
    (0xFF, 0x00, 0x00),  # 009 bright red
    (0x00, 0xFF, 0x00),  # 010 bright green
    (0xFF, 0xFF, 0x00),  # 011 bright yellow
    (0x00, 0x00, 0xFF),  # 012 bright blue
    (0xFF, 0x00, 0xFF),  # 013 bright magenta
    (0x00, 0xFF, 0xFF),  # 014 bright cyan
    (0xFF, 0xFF, 0xFF),  # 015 bright white
)

CUBE_LEVELS = (0x00, 0x5F, 0x87, 0xAF, 0xD7, 0xFF)
GRAYSCALE_STEPS = 24
SATURATION_CAP = 0.62

# Foregrounds only. Keep ANSI_16 raw for server-authored backgrounds.
NARRATIVE_ANSI = {
    1: (0xB8, 0x66, 0x5F),
    2: (0x7F, 0xA3, 0x7A),
    3: (0xC9, 0xAD, 0x78),
    4: (0x7B, 0x92, 0xC2),
    5: (0xA9, 0x87, 0xA9),
    6: (0x76, 0xA2, 0xAA),
    9: (0xDC, 0x7A, 0x72),
    10: (0x8F, 0xB9, 0x8A),
    11: (0xE4, 0xC8, 0x8E),  # --gold-400
    12: (0x8A, 0xA3, 0xD8),
    13: (0xC4, 0x96, 0xC4),
    14: (0x86, 0xB8, 0xC2),
}


def narrative_foreground(index: int, rgb: tuple[int, int, int]) -> tuple[int, int, int]:
    """Map raw foregrounds before contrast flooring; never map backgrounds."""
    if index in NARRATIVE_ANSI:
        return NARRATIVE_ANSI[index]
    if not 16 <= index < 232:
        return rgb
    hue, lightness, saturation = colorsys.rgb_to_hls(*(value / 255 for value in rgb))
    if saturation <= SATURATION_CAP:
        return rgb
    channels = colorsys.hls_to_rgb(hue, lightness, SATURATION_CAP)
    # Nearest rounding can push 8-bit saturation above the strict cap.
    return tuple(
        ceil(value * 255) if value < lightness
        else floor(value * 255) if value > lightness
        else round(value * 255)
        for value in channels
    )


def _relative_luminance(rgb: tuple[int, int, int]) -> float:
    """WCAG relative luminance of an sRGB triple."""

    def linear(channel: int) -> float:
        value = channel / 255.0
        if value <= 0.03928:
            return value / 12.92
        return ((value + 0.055) / 1.055) ** 2.4

    r, g, b = (linear(channel) for channel in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(fg: tuple[int, int, int], bg: tuple[int, int, int]) -> float:
    """WCAG contrast ratio between two sRGB triples."""
    light, dark = sorted(
        (_relative_luminance(fg), _relative_luminance(bg)), reverse=True
    )
    return (light + 0.05) / (dark + 0.05)


def _blend(toward: tuple[int, int, int], color: tuple[int, int, int]) -> tuple[int, int, int]:
    """Blend ``color`` 10% toward ``toward``."""
    return tuple(
        round((toward[i] * 0.1) + (color[i] * 0.9)) for i in range(3)
    )


def contrast_floored_foreground(rgb: tuple[int, int, int]) -> tuple[int, int, int]:
    """Blend toward the paper foreground until the contrast floor passes."""
    color = rgb
    steps = 0
    while contrast_ratio(color, INK) < CONTRAST_FLOOR and steps < BLEND_STEPS:
        color = _blend(PAPER, color)
        steps += 1
    return color


def build_palette() -> list[tuple[int, tuple[int, int, int]]]:
    """Return ``(index, rgb)`` for every color index 0..255."""
    palette: list[tuple[int, tuple[int, int, int]]] = []
    for index, rgb in enumerate(ANSI_16):
        palette.append((index, rgb))
    for r in CUBE_LEVELS:
        for g in CUBE_LEVELS:
            for b in CUBE_LEVELS:
                palette.append((len(palette), (r, g, b)))
    for step in range(GRAYSCALE_STEPS):
        value = 8 + step * 10
        palette.append((len(palette), (value, value, value)))
    assert len(palette) == 256, f"palette has {len(palette)} entries, expected 256"
    return palette


def build_stylesheet() -> str:
    """Render the full stylesheet text."""
    lines = [
        "/* ---",
        "",
        "  Generated by tools/gen_ansi_palette.py -- do not edit by hand.",
        "",
        "  ANSI/xterm-256 narrative palette. Muted ANSI and saturation-capped",
        "  cube foregrounds pass a deterministic contrast floor against #141019;",
        "  background entries are raw palette values. The `blink` class uses",
        "  Evennia's stock animation and degrades to a dotted underline under",
        "  `prefers-reduced-motion: reduce` and at the `reduced` and `off`",
        "  motion levels (`<html data-motion>`, webclient-motion-level).",
        "",
        "  web/webclient/tests/test_ansi_palette.py regenerates this file and",
        "  compares it byte-for-byte with the committed copy.",
        "",
        "--- */",
        "",
        ".underline { text-decoration: underline; }",
        "",
        ".blink {",
        "  animation: blink-animation 1s steps(5, start) infinite;",
        "  -webkit-animation: blink-animation 1s steps(5, start) infinite;",
        "}",
        "",
        "@keyframes blink-animation {",
        "  to {",
        "    visibility: hidden;",
        "  }",
        "}",
        "",
        "@-webkit-keyframes blink-animation {",
        "  to {",
        "    visibility: hidden;",
        "  }",
        "}",
        "",
        "@media (prefers-reduced-motion: reduce) {",
        "  .blink {",
        "    animation: none;",
        "    -webkit-animation: none;",
        "    text-decoration: underline dotted;",
        "  }",
        "}",
        "",
        ":root[data-motion=\"reduced\"] .blink,",
        ":root[data-motion=\"off\"] .blink {",
        "  animation: none;",
        "  -webkit-animation: none;",
        "  text-decoration: underline dotted;",
        "}",
        "",
    ]
    for index, rgb in build_palette():
        fg = contrast_floored_foreground(narrative_foreground(index, rgb))
        hex_value = "#{:02x}{:02x}{:02x}".format(*fg)
        lines.append(f".color-{index:03d} {{ color: {hex_value}; }}")
        bg_hex = "#{:02x}{:02x}{:02x}".format(*rgb)
        lines.append(f".bgcolor-{index:03d} {{ background-color: {bg_hex}; }}")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(build_stylesheet(), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
