# Generated by Django 6.0.7 on 2026-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NarrativeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("content", models.JSONField(default=dict)),
                ("participants", models.JSONField(default=list)),
                (
                    "location",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("tick", models.IntegerField(db_index=True, default=0)),
                ("visibility", models.CharField(default="public", max_length=32)),
                ("salience", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "narrative_events",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=255)),
                ("projector_version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "narrative_projection_progress",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "projector_version"),
                        name="unique_narrative_source_projector",
                    )
                ],
            },
        ),
    ]
