# Generated by Django 6.0.7 on 2026-10-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("narrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerMemoryGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("generation", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "narrative_owner_memory_generations",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MemoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=64)),
                ("tick", models.IntegerField(db_index=True, default=0)),
                ("category", models.CharField(db_index=True, default="observation", max_length=64)),
                ("content", models.JSONField(default=dict)),
                ("salience", models.IntegerField(default=1)),
                ("knowledge_scope", models.CharField(db_index=True, default="witnessed", max_length=32)),
                ("confidence", models.FloatField(default=1.0)),
                ("subjects", models.JSONField(default=list)),
                ("source_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("projector_version", models.IntegerField(blank=True, db_index=True, null=True)),
                ("derived_generation", models.IntegerField(blank=True, null=True)),
                ("effective_tier", models.CharField(db_index=True, default="working", max_length=32)),
                ("effective_availability", models.CharField(db_index=True, default="active", max_length=32)),
                ("latest_revision_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "narrative_memory_records",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MemoryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision_number", models.IntegerField(default=1)),
                ("availability", models.CharField(default="active", max_length=32)),
                ("tier", models.CharField(default="working", max_length=32)),
                ("decay_metadata", models.JSONField(default=dict)),
                ("supersedes_record_id", models.CharField(blank=True, default="", max_length=64)),
                ("relations", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="narrative.memoryrecord",
                    ),
                ),
            ],
            options={
                "db_table": "narrative_memory_revisions",
                "ordering": ["record", "revision_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="memoryrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(projector_version__isnull=False),
                fields=("owner_id", "source_id", "projector_version"),
                name="unique_owner_source_projector",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryrevision",
            constraint=models.UniqueConstraint(
                fields=("record", "revision_number"),
                name="unique_memory_record_revision",
            ),
        ),
    ]
