# Generated by Django 6.0.7 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrative", "0002_memory_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeContextSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.CharField(db_index=True, max_length=128, unique=True)),
                ("capability", models.CharField(db_index=True, max_length=64)),
                ("prompt_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(blank=True, default="", max_length=64)),
                ("rendering_version", models.CharField(max_length=64)),
                ("owner_id", models.CharField(db_index=True, max_length=64)),
                ("owner_generation", models.BigIntegerField(default=0)),
                ("sources", models.JSONField(default=list)),
                ("section_hashes", models.JSONField(default=dict)),
                ("budget_accounting", models.JSONField(default=dict)),
                ("truncation_decisions", models.JSONField(default=list)),
                ("rendered_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "narrative_context_snapshots",
                "ordering": ["id"],
            },
        ),
    ]
