# Generated by Django 6.0.7 on 2026-10-04 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrative", "0004_dialogue_turns"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=128, unique=True)),
                ("sender_id", models.CharField(max_length=64)),
                ("recipient_id", models.CharField(max_length=64)),
                ("recipient_kind", models.CharField(max_length=16)),
                ("body", models.TextField()),
                ("sent_tick", models.BigIntegerField()),
                ("due_tick", models.BigIntegerField(db_index=True)),
                ("reply_to", models.CharField(blank=True, default="", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="LetterState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_id", models.CharField(max_length=64)),
                ("due_tick", models.BigIntegerField()),
                ("status", models.CharField(default="sent", max_length=32)),
                (
                    "transition_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("collection_tick", models.BigIntegerField(null=True)),
                ("read_tick", models.BigIntegerField(null=True)),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="narrative.lettersend",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "due_tick"], name="letter_due_idx"),
                    models.Index(
                        fields=["recipient_id", "status"], name="letter_recipient_idx"
                    ),
                ],
            },
        ),
    ]
